# Generated by Django 4.1.3 on 2022-12-07 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTRAINEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=30)),
                ('DateEntrainement', models.DateField()),
                ('NomPartie1', models.CharField(max_length=30)),
                ('Partie1', models.TextField(max_length=254)),
                ('TempsPartie1', models.TimeField()),
                ('DistancePartie1', models.CharField(max_length=20)),
                ('NomPartie2', models.CharField(max_length=30)),
                ('Partie2', models.TextField(max_length=254)),
                ('TempsPartie2', models.TimeField()),
                ('DistancePartie2', models.CharField(max_length=20)),
                ('NomPartie3', models.CharField(max_length=30)),
                ('Partie3', models.TextField(max_length=254)),
                ('TempsPartie3', models.TimeField()),
                ('DistancePartie3', models.CharField(max_length=20)),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-DateCreation'],
            },
        ),
        migrations.CreateModel(
            name='ENTRAINEUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', encrypted_model_fields.fields.EncryptedCharField()),
                ('Prenom', encrypted_model_fields.fields.EncryptedCharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Tel', models.CharField(default='0699999999', max_length=20)),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('Identifiant', models.CharField(max_length=20)),
                ('Role', models.CharField(choices=[('Entraineur', 'Entraineur'), ('Entraineur Resp. Planning', 'Entraineur Resp. Planning')], default='Entraineur', max_length=50)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-DateCreation'],
            },
        ),
        migrations.CreateModel(
            name='COMMENTAIRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commentaire', models.TextField(max_length=254)),
                ('DateCommentaire', models.DateTimeField(auto_now_add=True)),
                ('EntrainementCommentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntrainementCommentaire', to='planning.entrainement')),
                ('UserCommentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentaire', to='planning.entraineur')),
            ],
            options={
                'ordering': ['-DateCommentaire'],
            },
        ),
        migrations.CreateModel(
            name='ATTRIBUER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAttribution', models.DateTimeField(auto_now_add=True)),
                ('EntrainementAttribuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntrainementAttribuer', to='planning.entrainement')),
                ('EntraineurAttribuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntraineurAttribuer', to='planning.entraineur')),
            ],
            options={
                'ordering': ['-DateAttribution'],
            },
        ),
    ]
